services:
  app:
    build: .
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      DATABASE_URL: "${DATABASE_URL}"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
